export * from './Genres'
export * from './HeaderCont'
export * from './Loadings'
export * from './MovieCont'
export * from './MovieDetailsCont'
export * from './HeaderCont/MovieMini'
export * from './MoviesCont'
export * from './Pagination'
export * from './Search'
export * from './Sortings'

